### PR TITLE
feat: add templateDir to allow reuse

### LINKED ISSUE #34: Support of template import in the freemarker engine
The aims are to support the freemarker macro feature in order to use the freemarker inline script like 

```
<#import "simple_macro.ftl" as myMacro><@myMacro.p >Hello world!</@myMacro.p>
```

with `simple_macro.ftl` deploying into a `templates` folder in the camunda classpath

```
<#macro p><p><#nested></p></#macro>
```

Using the external resource must also work : 

Using `freemarker/test.ftl` (in a different folder than `templates`) with the following `test.ftl` content : 

```
<#import "simple_macro.ftl" as simple>

<@simple.p>it works</@simple.p>
```

A related PR (tested with Camunda 7.20 is almost ready)

### PR DESCRIPTION
**Pull request by M3lkior**
Templates must be in a /templates dir, in the Camunda classpath.

See the README.md for examples usages.

Close #34

### CODE REVIEW

**Comment by psavidis** [comment]
Hello @M3lkior!

Thanks for the contribution. Could you elaborate a bit please on the purpose of this PR? What is the problem that it solves?

**Comment by M3lkior** [comment]
Hi @psavidis ; i explain my need in this linked issue: https://github.com/camunda/camunda-template-engines-jsr223/issues/34

Currently, using freemarker as template engine, it is not possible to use the `include` or `macro` features in the freemarker template because the template folder dir is not defined in the Camunda Freemarker wrapper.

My PR solves this limitation, allowing to compose freemarker content, using macro, or freemarker files inclusion. 
In my use case, and running my PR, i'm able to define a nested macro that encapsulate an HTML envelop (with proper headers, logo, footer, etc) for example. This macro is reused in each inline content or freemarker file defined in the script engine

**Comment by psavidis** [comment]
Hey @M3lkior,

Currently due to workload i still haven't had the chance to make a thorough testing on your contribution.
Will try to update as soon as i have news.

Best,
Petros

**Comment by psavidis** [comment]
Hello @M3lkior ,

I've tried to test your contribution and i couldn't make it work. Specifically:

I've used a simple bpmn process diagram with a script task that references a template file called `simple_macro.ftl` as indicated in the screenshot below:

Screenshot 2024-02-16 at 5 29 11 PM

- I've tried to test the tomcat distribution with your fix:
    - It only worked for me when i'm building `camunda-template-engines-jsr223` with a `templates` folder under resources and i place the file to be refenced there e.g `simple_macro.ftl` i've used in my example.
    - I've placed  the `simple_macro.ftl` template to be referenced under `/userlib/templates/` and the deployed process that uses the script task was failing with an exception that the template cannot be loaded.
    
One interesting aspect for this feature is its security concerns. We have to understand if it's acceptable to allow file references from `freemarker` templates.

I'd like to ask you to provide me with the specific steps to follow to test your contribution as i wasn't able to do so.

Best,
Petros

**Comment by M3lkior** [comment]
Hi @psavidis ;

Thanks to take time on this PR review / test;

I test this feature on local with the camunda-bpm-run-7.20.0 project : 

Here is what to do : 
- generation the `camunda-template-engines-jsr223` snapshot artifact and copy it under `userlib` (be carefull to disable the official artifact to avoid classpath conflict)
- create a `templates` folder under `userlib` and create the `simple_macro.ftl` with his content
- Try to run you BMMN from this instances

image

I currently use Camunda Run on GCP Cloud Run ; If you have access to a GCP project, you can quickly validate the same approach : 
 
- uploading the ftl files into a GCP bucket
- create this bucket as a GCP Cloud Run Volumes
- Install this volume in the expected `userlib/templates` folder
image
- you also need to mount an another volume to store the jar artifacts ; you can mount it in Cloud Run like this
image

Note that the GCS volumes definition is not already possible from the console, you need to directly edit the Cloud Run YAML: 
```
volumes:
      - name: camunda-ext-lib
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: any-camunda-classpath-binaries-bucket-name
      - name: camunda-ext-freemarker-templates
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: any-camunda-freemarker-templates-bucket-name
      - name: camunda-mail-config
        secret:
          secretName: camunda-mail-config
          items:
          - key: latest
            path: mail-config.properties
```

**Comment by psavidis** [comment]
Hello @M3lkior ,

Using the latest snapshot of `camunda-bpm-run-7.21.0-SNAPSHOT`, i followed your steps to test locally the code and it still doesn't work for me.

Below i attach the screenshots of `camunda-run` with the copied folders, the `camunda-template-engines-jsr223` jar and the `freemarker` template.

<details><summary>Camunda run structure screenshot</summary>
Screenshot 2024-03-01 at 1 00 27 PM
</details>

<details><summary>Exception screenshot</summary>
Screenshot 2024-03-01 at 12 59 32 PM
</details>

<details><summary>test_freemarker.bpmn screenshot</summary>
Screenshot 2024-03-01 at 1 05 18 PM
</details>

- The only working scenario so far has been only the case where the configuration folder needs to be built inside the `camunda-template-engines-jsr223` jar. 
- The above setup does not provide any meanigfull value from a user's perspective since having the ability to use `freemarker template` macros but also having to build the jar from the source code beats the original purpose of the feature: to be able to reference `ftl` files dynamically.

The above are not sufficient to consider this feature further at the moment. 
I'm closing this Pull Request for now. 
If you think your contribution is meaningful, feel free to open a new Pull Request with _simple instructions_ on how to test the code and state how the feature will be beneficial from a user's perspective.

Thank you for your interest,
Petros

**Pull request closed without merging**
